### ISSUE TITLE
Children props issue

### ISSUE THREAD

**Issue by avbelyaev-domclick** [jesseskinner/svelte-react#1]
Hello! Does `children` in your `ReactComponent` only accept text and not Svelte components?

I am trying to use it like so:
![image](https://user-images.githubusercontent.com/69820127/90440272-9cba3800-e0df-11ea-9c48-c7e1de2ba46d.png)
![image](https://user-images.githubusercontent.com/69820127/90440051-464cf980-e0df-11ea-9276-1b1e2f31342b.png)

But nothing is displayed. Only text works fine:
![image](https://user-images.githubusercontent.com/69820127/90440244-8f9d4900-e0df-11ea-88bc-f1acf1b27c07.png)

**Comment by avbelyaev-domclick** [comment]
@jesseskinner am I doing something wrong?

**Comment by jesseskinner** [comment]
I believe you can pass a Svelte component like that.. but then on the React side, you may need to use [react-svelte](https://github.com/Rich-Harris/react-svelte) to render the Svelte component inside React. I haven't tried that before - so let me know if you run into trouble.

**Comment by avbelyaev-domclick** [comment]
Yeah, I thought using `react-svelte` would help (I wrapped `Hello.svelte` in `ReactComponent`), but it sadly didn't :(

Thx for answering so quickly!

**Comment by jesseskinner** [comment]
No problem! Let me know how it goes.

**Comment by avbelyaev-domclick** [comment]
@jesseskinner this is how it goes when using `react-svelte`:
![image](https://user-images.githubusercontent.com/69820127/90441111-10107980-e0e1-11ea-8d4b-d79296d09d3d.png)

**upd:**
![image](https://user-images.githubusercontent.com/69820127/90441340-75646a80-e0e1-11ea-9367-8c30dd58eadb.png)

**upd 2**. cant seem to get it to work..:
![image](https://user-images.githubusercontent.com/69820127/90441400-8e6d1b80-e0e1-11ea-989f-866b0f763609.png)

**Comment by avbelyaev-domclick** [comment]
Almost got this working with https://github.com/pngwn/svelte-adapter#react

It is calling the Svelte component but in the wrong context I guess:
![image](https://user-images.githubusercontent.com/69820127/90446508-2c64e400-e0ea-11ea-8187-4499e5333bb6.png)

**Comment by avbelyaev-domclick** [comment]
I got it working!

**Comment by avbelyaev-domclick** [comment]
@jesseskinner sent a PR which allows one to pass React component (or Svelte component wrapped in [svelte-adapter](https://github.com/pngwn/svelte-adapter#react)'s `toReact(SvelteComponent)` function) when using your helpful library!

Should not break any existing functionality.

**Comment by avbelyaev-domclick** [comment]
@jesseskinner ok to merge?

**Comment by jesseskinner** [comment]
@avbelyaev-domclick Thanks so much! I would like to add some tests somehow to make sure it's working for all cases. I was planning to take a look at that in a few hours on my [Twitch stream](https://twitch.tv/jesseskinner). I'll let you know how it goes.

**Comment by jesseskinner** [comment]
@avbelyaev-domclick Thanks a lot for the pull request. I was thinking though, that children can be functions, although that's not as popular these days as it used to be, it certainly works, and is used in some libraries, for example [react-motion](https://github.com/chenglou/react-motion).

Perhaps the solution could be that you call `React.createElement` in the same place you're called `toReact`, eg.

```html
<ReactComponent this={Hello} children={React.createElement(toReact(Child), { prop:1 })} />
```

I think it'd be better left this way, because that'll give you the opportunity to pass props and children in to your children as you instantiate them. Would that work?

**Comment by avbelyaev-domclick** [comment]
@jesseskinner hey, I am actually using children as a function, and it works! (but without my PR it doesn't, have you tried?)

Also, I really don't like the idea of writing `React.` code in `.svelte` components - I don't even directly depend on React, only on `svelte-react` and `svelte-adapter`. What do you think?
**UPD:** What I mean is, your library and `svelte-adapter` abstract `React` away from consumer `Svelte` apps, and that's cool.

**Comment by avbelyaev-domclick** [comment]
@jesseskinner the way your library currently works, passing any Svelte or React component to `children` will yield no results*. With this PR at least passing React components is indeed working without further modifications. And passing Svelte components works with `toReact` as mentioned.

*by no results I mean this error message:
![image](https://user-images.githubusercontent.com/69820127/90555353-e79b8480-e19f-11ea-9da3-909644367039.png)

**Comment by avbelyaev-domclick** [comment]
Currently `children` only support passing `string`, `number` or any other JS primitive, and they will be displayed as is. Not much of a use, I'd say.

Please correct me if I am wrong in any of the statements above.

**Comment by jesseskinner** [comment]
I added a test that shows the use of a function passed to the children prop, it works fine.

Calling `React.createElement` would break this test. Although this approach works for your use case, it excludes use cases where you want to pass props or additional children (grandchildren?) to the React component. Calling `React.createElement` in your Svelte code is ugly, but would give you that flexibility.

I think it'd be nice to find a solution where it's a lot easier to mix React and Svelte components like this, but unfortunately I think that's out of the scope of this library.

**Comment by avbelyaev-domclick** [comment]
>Calling React.createElement in your Svelte code is ugly, but would give you that flexibility.

Okay... (
